### ISSUE TITLE
Are all algorithms on DomainNet reproduces by 15k iterations?

### ISSUE THREAD

**Issue by Luodian** [khanrc/swad#12]
Hi thanks for providing such great work to us. I noticed that MIRO and SWAD results on DomainNet are increased from 5k to 15k iterations. I am curious are all other algorithms in this table reproduced by 15k iterations?

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/15847405/167244557-5e6dd6a1-2933-411a-99b0-aac907d2d1f9.png">

**Comment by khanrc** [comment]
As written in the caption, only `ERM (reproduced)` and `MixStyle` are reproduced results (15k iteration). The dagger-marked results  are from DomainBed (5k) and the rest results (DMG and MetaReg) are from DMG paper (probably over 15k).

We considered to reproduce all the algorithms from DomainBed with 15k iterations, but the required computational resource was not affordable.

**Comment by Luodian** [comment]
THANKS! It's really meaningful.
