### ISSUE TITLE
about the results

### ISSUE THREAD

**Issue by Cassiatora** [khanrc/swad#14]
Hi, thanks for your work. Can I ask a question? what's the meaning of the result "test_in     test_out    train_in    train_out"?

**Comment by khanrc** [comment]
"train_in" indicates performance of training dataset, "train_out" indicates performance of validation dataset, and "test_in" indicates performance of test dataset. "test_out" is used for oracle model selection method in DomainBed paper, but it is not used in our work.

**Comment by Cassiatora** [comment]
> "train_in" indicates performance of training dataset (in-domain), "train_out" indicates performance of validation dataset (in-domain), and "test_in" indicates performance of test dataset (out-of-domain). "test_out" is used for oracle model selection method in DomainBed paper, but it is not used in our work.

OK. The explanation is very clear. Thank you for your quick reply.
