### ISSUE TITLE
it's not running correct 

### ISSUE THREAD

**Issue by frangkyy** [khanrc/swad#16]
for this :
  INFO 08/30 14:28:23 | Target test envs = [[0]]
  INFO 08/30 14:28:23 | test_envs:[0]
  
  INFO 08/30 14:28:23 | Testenv name escaping te_kfold -> te_kfold
  INFO 08/30 14:28:23 | Test envs = [0], name = te_kfold
  INFO 08/30 14:28:23 | Batch sizes for each domain: [0] (total=0)
  
  Traceback (most recent call last):
    File "train_all.py", line 184, in <module>
      main()
    File "train_all.py", line 161, in main
      writer=writer,
    File "/home/attrsense_xianjun/VsCodePoject/swad-main/domainbed/trainer.py", line 93, in train
      steps_per_epoch = min(steps_per_epochs)
  ValueError: min() arg is an empty sequence

my code is  :
python train_all.py PACS0 --dataset PACS --deterministic --trial_seed 0 --checkpoint_freq 100 --data_dir ./data/
but I don't know why

**Comment by khanrc** [comment]
It seems to be a problem about data directory structure. Please check if the data is located and structured correctly.
