### ISSUE TITLE
download_office_home link error

### ISSUE THREAD

**Issue by ShijianXu** [khanrc/swad#17]
Hi,

The link to download OfficeHome is forbiddened. Is the dataset downloaded from the original URL the same as the dataset downloaded from your provided URL?

Best regards.

**Comment by khanrc** [comment]
We updated the download link, following [DomainBed@5fa8fe7](https://github.com/facebookresearch/DomainBed/commit/5fa8fe7cb5ae8f64c06f721cc3a6f12d9c78990f). Thank you for letting me know.
