### ISSUE TITLE
The results of SAM 

### ISSUE THREAD

**Issue by Wang-pengfei** [khanrc/swad#20]
Thanks for your impressive work. Could you provide the results of SAM for each domain on the 5 datasets? Thank you very much.

**Comment by khanrc** [comment]
I find these results from my old log file, so please use the results as just reference.


PACS |   |   |   |   |  
-- | -- | -- | -- | -- | --
Algorithm | A | C | P | S | Avg
SAM | 85.6 ± 2.1  | 80.9 ± 1.2  | 96.9 ± 0.4  | 79.6 ± 1.6  | 85.8


VLCS |   |   |   |   |  
-- | -- | -- | -- | -- | --
Algorithm | C | L | S | V | Avg.
SAM | 99.1 ± 0.2 | 65.0 ± 1.0 | 73.7 ± 1.0 | 79.8 ± 0.1 | 79.4


OfficeHome |   |   |   |   |  
-- | -- | -- | -- | -- | --
Algorithm | A | C | P | R | Avg.
SAM | 64.5 ± 0.3 | 56.5 ± 0.2 | 77.4 ± 0.1 | 79.8 ± 0.4 | 69.6


TerraIncognita |   |   |   |   |  
-- | -- | -- | -- | -- | --
Algorithm | L100 | L38 | L43 | L46 | Avg.
SAM | 46.3 ± 1.0 | 38.4 ± 2.4 | 54.0 ± 1.0 | 34.5 ± 0.8 | 43.3


DomainNet |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | --
Algorithm | C | I | P | Q | R | S | Avg.
SAM | 64.5 ± 0.3 | 20.7 ± 0.2 | 50.2 ± 0.1 | 15.1 ± 0.3 | 62.6 ± 0.2  | 52.7 ± 0.3 | 44.3

**Comment by Wang-pengfei** [comment]
Thanks!
