### ISSUE TITLE
How to draw Figure 4?

### ISSUE THREAD

**Issue by WentaoTan** [khanrc/swad#21]
This is a beautifully drawn picture!
Can you tell me how to draw this kind of loss value and model parameter correlation diagram?

**Comment by khanrc** [comment]
We release the reference code to help. See https://github.com/khanrc/swad/tree/main/visualization.

**Comment by WentaoTan** [comment]
I'm sorry to bother you again, but I've looked at the code in the visualization folder and the SWA related code, and I still don't understand it, and I've encountered a lot of errors. The main problems are:
(1) The import file infer_utils is empty.
(2) What is the content of the file with the suffix "*.pth"?

Thanks a lot!

**Comment by khanrc** [comment]
As written in the README, the visualization code is provided for reference only, not for execution. `*.pth` files indicate checkpoints. [This code](https://github.com/timgaripov/dnn-mode-connectivity/blob/master/plane.py), which is our original reference code, may help you better.
