### ISSUE TITLE
Questions about the algorithm

### ISSUE THREAD

**Issue by Crestina2001** [khanrc/swad#22]
In trainer.py, you define swad_algorithm as: swad_algorithm = swa_utils.AveragedModel(algorithm)
So swad_algorithm averages the parameters of the first n steps
And in swad.py, you use swad_algorithm as segment_swa in LossValley.update_and_evaluate() function in this way:
        frozen = copy.deepcopy(segment_swa.cpu())
        frozen.end_loss = val_loss
        self.converge_Q.append(frozen)
        self.smooth_Q.append(frozen)
So frozen is swa_utils.AveragedModel which averages the parameters of the first n steps?
But I think it should be the parameters of every single step, as suggested in the paper.

**Comment by khanrc** [comment]
SWAD averages every single step.

It is a kind of engineering trick to get a model using SWAD by a single run. `swad_algorithm` in `trainer.py` corresponds to `segment_swa` of `swad.py` ([as commented](https://github.com/khanrc/swad/blob/main/domainbed/trainer.py#L178-L180)). It averages every single step in a segment (every step between two evaluation points). The `swad_algorithm` (=`segment_swa`) is updated again with `swad` (https://github.com/khanrc/swad/blob/main/domainbed/trainer.py#L249-L251). In summary, `swad_algorithm` averages every step between two evaluation points (segment), and `swad` averages the `swad_algorithm`s, resulting in averaging every single step.

**Comment by Crestina2001** [comment]
Oh, I get it.
Thank you very much for your reply.
