### ISSUE TITLE
A question about  turning off SWAD

### ISSUE THREAD

**Issue by winerholiday** [khanrc/swad#24]
Hello, I want to say thank you for your great work first!

 I want to know how to performance the algorithms without SWAD. In other words, how can I turn off the SWAD.. I don't find any hyper-parameters to make it.

Thanks!!

**Comment by khanrc** [comment]
https://github.com/khanrc/swad/blob/main/config.yaml#L4
Set `swad` option to `null` here.

**Comment by winerholiday** [comment]
Thanks！！
