### ISSUE TITLE
[Query]: ERM results with no swad

### ISSUE THREAD

**Issue by lakpa-tamang9** [khanrc/swad#27]
Hi I have tried reproduced results of existing algorithm without using swad by setting `swad` to `null` in config. I have obtained following results when algorithm is set to `ERM`. Here, what value should i use that represents the ERM results? Similar to when `swad: LossValley`, the results table had row named `SWAD`.

+------------+--------------+---------+---------+---------+---------+
| Selection  | art_painting | cartoon |  photo  |  sketch |   Avg.  |
+------------+--------------+---------+---------+---------+---------+
|   oracle   |   89.201%    | 82.623% | 97.455% | 83.174% | 88.113% |
|    iid        |   86.882%    | 78.252% | 96.108% | 76.877% | 84.530% |
|    last      |   82.123%    | 79.371% | 95.883% | 74.873% | 83.063% |
| last (inD) |   96.489%    | 94.535% | 95.341% | 95.446% | 95.453% |
| iid (inD)  |   97.130%    | 96.569% | 96.462% | 96.735% | 96.724% |
+------------+--------------+---------+---------+---------+---------+

**Comment by khanrc** [comment]
The `iid` row is the results of the training-validation model selection method.
