### ISSUE TITLE
about the result

### ISSUE THREAD

**Issue by chenruolin2019** [khanrc/swad#7]
Could I ask a question?
What's the difference between the result "env0_in" and "env0_out"?

**Comment by khanrc** [comment]
![image](https://user-images.githubusercontent.com/3657248/150053863-ce1fb961-fe2c-42ad-824b-c84c19ee2a31.png)
(image adopted from the DomainBed paper)

"env0_in" indicates big split of domain 0, and "env0_out" indicates small split of domain 0.

**Comment by chenruolin2019** [comment]
OK thank you very much！And, what's the meaning of the result "**oracle**, **iid**, and **last**" and the difference among them?

**Comment by khanrc** [comment]
See #1.

**Comment by chenruolin2019** [comment]
Ok, thank you! I have an another question:
python train_all.py PACS0 --dataset PACS --deterministic --trial_seed 0 --checkpoint_freq 100 --data_dir /my/datasets/path
When I run this, the oracle and iid are the same reslut. Why?

**Comment by khanrc** [comment]
The best `iid` checkpoint and the `oracle` checkpoint can be same (but usually not). Are they always same, even with different HPs or `trial_seed`?

**Comment by chenruolin2019** [comment]
Some results are the same, some are different.

**Comment by khanrc** [comment]
If so, it is normal.
